---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages:
  - commit
repos:
  - repo:            https://github.com/pre-commit/pre-commit-hooks
    rev:             v3.4.0
    hooks:
      - id:          trailing-whitespace
        stages:      [ commit ]
      - id:          end-of-file-fixer
        stages:      [ commit ]
      - id:          check-yaml
      - id:          check-added-large-files
  - repo:            local
    hooks:
      - id:          eslint
        name:        Editor Config lint
        entry:       eclint check
        description: This hook runs the local installation of eclint.
        language:    node
        types:       [ file ]
      - id:          gitlint
        name:        Git lint
        entry:       gitlint
        description: This hook runs the local installation of gitlint.
        language:    python
        stages:      [ commit-msg ]
        args:        [ --staged, --msg-filename ]
      - id:          yamllint
        name:        Yaml lint
        entry:       yamllint
        description: This hook runs the local installation of yamllint.
        language:    python
        types:       [ file, yaml ]
